name: customer-support-sft
channels:
  - conda-forge
  - defaults

dependencies:
  - python=3.12
  - pip
  - pip:
      - torch==2.5.1
      - transformers==4.46.3
      - datasets==3.1.0
      - accelerate==1.0.1
      - peft==0.13.2
      - trl==0.12.1
